// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/cards.proto

package cards

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v3/api"
	client "github.com/micro/go-micro/v3/client"
	server "github.com/micro/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Cards service

func NewCardsEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Cards service

type CardsService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Cards_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Cards_PingPongService, error)
}

type cardsService struct {
	c    client.Client
	name string
}

func NewCardsService(name string, c client.Client) CardsService {
	return &cardsService{
		c:    c,
		name: name,
	}
}

func (c *cardsService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Cards.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardsService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Cards_StreamService, error) {
	req := c.c.NewRequest(c.name, "Cards.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &cardsServiceStream{stream}, nil
}

type Cards_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type cardsServiceStream struct {
	stream client.Stream
}

func (x *cardsServiceStream) Close() error {
	return x.stream.Close()
}

func (x *cardsServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *cardsServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *cardsServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *cardsServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cardsService) PingPong(ctx context.Context, opts ...client.CallOption) (Cards_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Cards.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &cardsServicePingPong{stream}, nil
}

type Cards_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type cardsServicePingPong struct {
	stream client.Stream
}

func (x *cardsServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *cardsServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *cardsServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *cardsServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *cardsServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *cardsServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Cards service

type CardsHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Cards_StreamStream) error
	PingPong(context.Context, Cards_PingPongStream) error
}

func RegisterCardsHandler(s server.Server, hdlr CardsHandler, opts ...server.HandlerOption) error {
	type cards interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Cards struct {
		cards
	}
	h := &cardsHandler{hdlr}
	return s.Handle(s.NewHandler(&Cards{h}, opts...))
}

type cardsHandler struct {
	CardsHandler
}

func (h *cardsHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.CardsHandler.Call(ctx, in, out)
}

func (h *cardsHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.CardsHandler.Stream(ctx, m, &cardsStreamStream{stream})
}

type Cards_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type cardsStreamStream struct {
	stream server.Stream
}

func (x *cardsStreamStream) Close() error {
	return x.stream.Close()
}

func (x *cardsStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *cardsStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *cardsStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *cardsStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *cardsHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.CardsHandler.PingPong(ctx, &cardsPingPongStream{stream})
}

type Cards_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type cardsPingPongStream struct {
	stream server.Stream
}

func (x *cardsPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *cardsPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *cardsPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *cardsPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *cardsPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *cardsPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
